image: docker:stable-git

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test

build_product_a:
  stage: build
  script:
    - docker build .
  tags:
    - docker

build_product_b:
  stage: build
  script:
    - docker build .
  tags:
    - docker

build_product_c:
  stage: build
  script:
    - docker build .
  tags:
    - docker
