image: docker:stable-git

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test

build_product_a:
  stage: build
  script:
    - pip install -r requirements.txt
  tags:
    - docker
